// Code generated by `mygo generate`. DO NOT EDIT.

import { call, event, type Channel } from "mygo-runtime";

// ---- Types ----

export interface BootstrapStatus {
  phase: string;
  ready: boolean;
  error: string;
}

export interface Capture {
  id: string;
  requestId?: string;
  phase: string;
  ts: string;
  method: string;
  url: string;
  host: string;
  status?: number;
  headers: Record<string, unknown>;
  body: string;
  bodyTruncated: boolean;
  source: string;
}

/** CaptureNotice is the typed event delivered to one MyGo Channel subscriber. */
export interface CaptureNotice {
  kind: string;
  capture?: Capture;
  enabled?: boolean;
  clientId?: string;
}

export interface CertificateState {
  trusted: boolean;
  installed: boolean;
  name: string;
  fingerprint: string;
  expiresAt: string;
}

export interface ClickRequest {
  path?: string[];
  expectedPid?: number;
  text: string;
  clickCount: number;
  matchOrdinal?: number;
  matchCount?: number;
}

export interface ClientLog {
  id: string;
  at: string;
  level: string;
  source: string;
  message: string;
  detail: string;
}

export interface Connection {
  provider: string;
  host: string;
  port: number;
}

export interface ConnectionStatus {
  active: Connection;
  saved: Connection;
  tokenConfigured: boolean;
  restartRequired: boolean;
  captureProxyAddress: string;
  captureProxyReady: boolean;
}

export interface CourseTargetRequest {
  path: string[];
  expectedPid?: number;
}

export interface CreateTaskInput {
  name: string;
  videos: TaskVideoInput[];
}

export interface DeleteResult {
  deleted: string[];
  cleanupPending: boolean;
}

export interface Diagnosis {
  checkedAt: string;
  go: string;
  player: Player | null;
  knownPlayers: Record<string, string>;
  checks: DiagnosticCheck[];
  environmentAppMd5Configured: boolean;
}

/**
 * DiagnosticCheck is one row of the environment page. Rows are produced grouped
 * by Group, in display order.
 */
export interface DiagnosticCheck {
  group: string;
  name: string;
  ok: boolean;
  message: string;
}

export interface Element {
  role: string;
  title?: string;
  value?: string;
  placeholder?: string;
  identifier?: string;
  width?: number;
  depth?: number;
  level?: number;
  canExpand?: boolean;
  expanded?: boolean;
}

export interface Entry {
  id: number;
  time: string;
  level: string;
  message: string;
  detail: string;
  scope?: string;
}

export interface FileChoice {
  id: string;
  name: string;
}

export interface Finished {
  id: string;
  status: string;
  total: number;
  completed: number;
  failed: number;
}

export interface HealthStatus {
  ok: boolean;
  count: number;
  captureEnabled: boolean;
  lastReceivedAt: string | null;
  connectedClients: number;
  serverTime: string;
  runtime: string;
}

export interface ImportedVideo {
  id: string;
  name: string;
}

export interface Job {
  id: string;
  taskId: string;
  name: string;
  createdAt: string;
  startedAt?: string;
  finishedAt?: string;
  status: string;
  retryable: boolean;
  attempt: number;
  progress?: Progress;
  error?: string;
  result?: unknown;
}

export interface JobLogChunk {
  data: string;
  offset: number;
  hasMore: boolean;
}

/**
 * LocalVideo describes a file selected with the native dialog or dropped on
 * the window. The path remains local to the page and is rechecked on import.
 */
export interface LocalVideo {
  path: string;
  name: string;
  size: number;
  modifiedTime: number;
  error?: string;
}

export interface Log {
  id: string;
  at: string;
  level: string;
  source: string;
  message: string;
  detail: string;
  requestId: string;
}

export interface LogPage {
  items: Log[];
  total: number;
  page: number;
  pageSize: number;
}

export interface LogQuery {
  level: string;
  source: string;
  search: string;
  from: string;
  to: string;
  page: number;
  pageSize: number;
}

export interface Player {
  softwareName: string;
  appMd5: string;
}

export interface PlayerSettings {
  mode: string;
  softwareName: string;
  appMd5: string;
}

export interface Progress {
  stage: string;
  done: number;
  total: number;
  elapsed: number;
  stage_elapsed: number;
  unit?: string;
}

/**
 * ReadIssue marks a retryable observation failure. Elements remain available
 * for blocking-dialog detection, but must not advance playback or completion.
 */
export interface ReadIssue {
  code: string;
  message: string;
}

export interface ResourceItem {
  id: string;
  name: string;
  size: number;
  finishedAt: string;
}

export interface ResourcePage {
  items: ResourceItem[];
  total: number;
  page: number;
}

export interface ResourceQuery {
  page: number;
  pageSize: number;
  search: string;
}

export interface Settings {
  keepAwake: boolean;
}

export interface Snapshot {
  running: boolean;
  elements: Element[];
  at: string;
  pid?: number;
  windowMode?: string;
  readIssue?: ReadIssue;
}

export interface State {
  stage: string;
  message: string;
  proxyAddress: string;
  receiverUrl: string;
  tokenConfigured: boolean;
  captureEnabled: boolean;
  received: number;
  logs: Entry[];
}

export interface Status {
  platform: string;
  installed: boolean;
  running: boolean;
  accessibilityReady: boolean;
  verifiedProfile: boolean;
  version?: string;
  message: string;
}

export interface TaskCounts {
  total: number;
  active: number;
  completed: number;
  failed: number;
}

export interface TaskList {
  files: FileChoice[];
  keys: FileChoice[];
  tasks: View[];
  jobs: Job[];
}

export interface TaskSummary {
  tasks: TaskCounts;
  videos: TaskCounts;
}

export interface TaskVideoInput {
  sourceId: string;
  uploadId: string;
  keyId: string;
  keyJson: string;
}

export interface VideoImportProgress {
  copied: number;
  total: number;
}

export interface View {
  id: string;
  name: string;
  createdAt: string;
  jobIds: string[];
  status: string;
  total: number;
  completed: number;
  failed: number;
  children: Job[];
}

// ---- Services ----

/** CaptureService exposes the native capture and certificate operations. */
export const CaptureService = {
  certificate(): Promise<CertificateState> {
    return call("CaptureService.Certificate");
  },
  clearLogs(): Promise<void> {
    return call("CaptureService.ClearLogs");
  },
  install(): Promise<CertificateState> {
    return call("CaptureService.Install");
  },
  regenerate(): Promise<CertificateState> {
    return call("CaptureService.Regenerate");
  },
  retry(): Promise<void> {
    return call("CaptureService.Retry");
  },
  state(): Promise<State> {
    return call("CaptureService.State");
  },
  trust(): Promise<CertificateState> {
    return call("CaptureService.Trust");
  },
} as const;

/** PlayerService contains only the visible, bounded SzPlayer operations. */
export const PlayerService = {
  click(request: ClickRequest): Promise<void> {
    return call("PlayerService.Click", request);
  },
  courseSnapshot(): Promise<Snapshot> {
    return call("PlayerService.CourseSnapshot");
  },
  expandFolder(name: string): Promise<void> {
    return call("PlayerService.ExpandFolder", name);
  },
  openCourse(path: string): Promise<void> {
    return call("PlayerService.OpenCourse", path);
  },
  openPermissionSettings(): Promise<void> {
    return call("PlayerService.OpenPermissionSettings");
  },
  /**
   * OpenPlayer launches the installed SzPlayer by its bundle identifier, so it works
   * wherever the app is installed. Orchestration itself only exists on macOS.
   */
  openPlayer(): Promise<void> {
    return call("PlayerService.OpenPlayer");
  },
  playbackSnapshot(): Promise<Snapshot> {
    return call("PlayerService.PlaybackSnapshot");
  },
  revealAppForPermission(): Promise<void> {
    return call("PlayerService.RevealAppForPermission");
  },
  revealCourse(request: CourseTargetRequest): Promise<Snapshot> {
    return call("PlayerService.RevealCourse", request);
  },
  setFullscreen(enabled: boolean): Promise<void> {
    return call("PlayerService.SetFullscreen", enabled);
  },
  setPlaybackRate(rate: number): Promise<void> {
    return call("PlayerService.SetPlaybackRate", rate);
  },
  setVolume(percent: number): Promise<void> {
    return call("PlayerService.SetVolume", percent);
  },
  snapshot(): Promise<Snapshot> {
    return call("PlayerService.Snapshot");
  },
  status(): Promise<Status> {
    return call("PlayerService.Status");
  },
  togglePlayback(): Promise<void> {
    return call("PlayerService.TogglePlayback");
  },
  /** Wait keeps orchestration timing in the native process when WKWebView is hidden. */
  wait(milliseconds: number): Promise<void> {
    return call("PlayerService.Wait", milliseconds);
  },
} as const;

/** NotificationService sends desktop notifications through MyGo's native API. */
export const NotificationService = {
  show(title: string, body: string, route: string): Promise<void> {
    return call("NotificationService.Show", title, body, route);
  },
} as const;

/**
 * WorkspaceService is the typed MyGo boundary for ordinary workspace data.
 * Media bytes and downloads use Protocol; capture events use Channel.
 */
export const WorkspaceService = {
  appendLogs(entries: ClientLog[]): Promise<void> {
    return call("WorkspaceService.AppendLogs", entries);
  },
  /** BootstrapStatus remains callable while workspace services start. */
  bootstrapStatus(): Promise<BootstrapStatus> {
    return call("WorkspaceService.BootstrapStatus");
  },
  captureState(): Promise<boolean> {
    return call("WorkspaceService.CaptureState");
  },
  /** ChooseVideoFiles opens the native picker attached to the calling window. */
  chooseVideoFiles(): Promise<LocalVideo[]> {
    return call("WorkspaceService.ChooseVideoFiles");
  },
  clearLogs(scope: string): Promise<number> {
    return call("WorkspaceService.ClearLogs", scope);
  },
  clearTraces(clientID: string): Promise<void> {
    return call("WorkspaceService.ClearTraces", clientID);
  },
  connection(): Promise<ConnectionStatus> {
    return call("WorkspaceService.Connection");
  },
  /** CopyText uses the native clipboard without auditing potentially sensitive text. */
  copyText(text: string): Promise<void> {
    return call("WorkspaceService.CopyText", text);
  },
  createTask(input: CreateTaskInput): Promise<View> {
    return call("WorkspaceService.CreateTask", input);
  },
  deleteTasks(ids: string[]): Promise<DeleteResult> {
    return call("WorkspaceService.DeleteTasks", ids);
  },
  diagnose(): Promise<Diagnosis> {
    return call("WorkspaceService.Diagnose");
  },
  health(): Promise<HealthStatus> {
    return call("WorkspaceService.Health");
  },
  history(limit: number): Promise<Capture[]> {
    return call("WorkspaceService.History", limit);
  },
  /**
   * ImportVideo streams local copy progress over a channel. Closing it cancels
   * the copy and removes the partial file.
   */
  importVideo(choice: LocalVideo, updates: Channel<VideoImportProgress>): Promise<ImportedVideo> {
    return call("WorkspaceService.ImportVideo", choice, updates);
  },
  /** InspectVideoFiles validates paths from MyGo's native file-drop event. */
  inspectVideoFiles(paths: string[]): Promise<LocalVideo[]> {
    return call("WorkspaceService.InspectVideoFiles", paths);
  },
  jobLogs(id: string, offset: number): Promise<JobLogChunk> {
    return call("WorkspaceService.JobLogs", id, offset);
  },
  keyHistory(): Promise<string> {
    return call("WorkspaceService.KeyHistory");
  },
  logs(query: LogQuery): Promise<LogPage> {
    return call("WorkspaceService.Logs", query);
  },
  powerSettings(): Promise<Settings> {
    return call("WorkspaceService.PowerSettings");
  },
  resources(query: ResourceQuery): Promise<ResourcePage> {
    return call("WorkspaceService.Resources", query);
  },
  retryTask(taskID: string, jobIDs: string[]): Promise<View> {
    return call("WorkspaceService.RetryTask", taskID, jobIDs);
  },
  saveKeyHistory(raw: string): Promise<string> {
    return call("WorkspaceService.SaveKeyHistory", raw);
  },
  savePowerSettings(settings: Settings): Promise<Settings> {
    return call("WorkspaceService.SavePowerSettings", settings);
  },
  saveSettings(input: PlayerSettings): Promise<PlayerSettings> {
    return call("WorkspaceService.SaveSettings", input);
  },
  setCaptureState(enabled: boolean): Promise<boolean> {
    return call("WorkspaceService.SetCaptureState", enabled);
  },
  settings(): Promise<PlayerSettings> {
    return call("WorkspaceService.Settings");
  },
  /**
   * Subscribe streams the initial receiver state followed by capture changes.
   * Closing the frontend channel cancels the Go context and releases its hub slot.
   */
  subscribe(notices: Channel<CaptureNotice>): Promise<void> {
    return call("WorkspaceService.Subscribe", notices);
  },
  summary(): Promise<TaskSummary> {
    return call("WorkspaceService.Summary");
  },
  tasks(): Promise<TaskList> {
    return call("WorkspaceService.Tasks");
  },
} as const;

/** LifecycleService keeps the renderer alive until its capture journal is saved. */
export const LifecycleService = {
  /** FinishQuit ignores stale acknowledgements, including a late timeout result. */
  finishQuit(id: number, failure: string): Promise<void> {
    return call("LifecycleService.FinishQuit", id, failure);
  },
  quit(): Promise<void> {
    return call("LifecycleService.Quit");
  },
  relaunch(): Promise<void> {
    return call("LifecycleService.Relaunch");
  },
  rendererReady(): Promise<void> {
    return call("LifecycleService.RendererReady");
  },
} as const;

// ---- Events ----

/** Events sent by the Go side. Subscribe with `events.name.on(listener)`. */
export const events = {
  desktopQuitRequested: event<number>("desktop:quit-requested"),
  /** Navigate is delivered from the native menu to the Vue router. */
  desktopNavigate: event<string>("desktop:navigate"),
  desktopDecryptTaskFinished: event<Finished>("desktop:decrypt-task-finished"),
} as const;
